# Default values for Ollama
# This chart deploys Ollama as a third competitor to vLLM and TGI

# Override the name of the chart
nameOverride: ""
fullnameOverride: ""

# Namespace override (default: release namespace)
namespace: ""

# Number of Ollama replicas
replicaCount: 1

# Container image configuration
image:
  repository: docker.io/ollama/ollama
  tag: "latest"
  pullPolicy: IfNotPresent

# Image pull secrets for private registries
imagePullSecrets: []

# Configuration for this Ollama instance
config:
  name: "ollama-competitor"
  description: "Ollama deployment for vLLM and TGI comparison"

# Ollama server configuration
ollama:
  # Model to serve (will be pulled automatically)
  model: "qwen2.5:7b"
  
  # Server port
  port: 11434
  
  # Ollama server arguments and configuration
  args: []
  
  # Model pull configuration
  modelPull:
    enabled: true
    # Additional models to pre-pull
    additionalModels: []
    # - "qwen2.5:0.5b"
    # - "llama3.1:8b"
  
  # Additional environment variables
  env:
    - name: OLLAMA_HOST
      value: "0.0.0.0:11434"
    - name: OLLAMA_ORIGINS
      value: "*"
    - name: OLLAMA_KEEP_ALIVE
      value: "5m"
    - name: OLLAMA_NUM_PARALLEL
      value: "4"
    - name: OLLAMA_MAX_LOADED_MODELS
      value: "1"
  
  # Additional volume mounts
  additionalVolumeMounts: []
  
  # Additional volumes
  additionalVolumes: []

# HuggingFace configuration (for compatible models)
huggingface:
  # HuggingFace token for accessing gated models (not typically needed for Ollama)
  token: ""

# Service configuration
service:
  type: ClusterIP
  port: 11434
  # nodePort: 30434  # Only used if type is NodePort

# OpenShift Route configuration
route:
  enabled: true
  host: ""
  path: ""
  annotations: {}
  tls: {}

# Storage configuration
storage:
  enabled: true
  size: 100Gi  # Larger size for Ollama models
  accessModes:
    - ReadWriteOnce
  storageClass: ""  # Use default storage class
  shmSize: 2Gi  # Shared memory size for /dev/shm
  selector: {}

# Resource configuration
resources:
  limits:
    cpu: "4"
    memory: 32Gi  # More memory for Ollama model loading
    nvidia.com/gpu: 1  # GPU for better performance
  requests:
    cpu: "2"
    memory: 16Gi
    nvidia.com/gpu: 1

# Health check configuration
healthCheck:
  enabled: true
  readiness:
    path: /api/tags
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  liveness:
    path: /api/tags
    initialDelaySeconds: 120
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 3
  startup:
    path: /api/tags
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 10
    failureThreshold: 40  # Allow up to 10 minutes for model loading

# Monitoring configuration
monitoring:
  enabled: false
  port: 11434
  path: /metrics
  serviceMonitor:
    enabled: false
    interval: 30s
    scrapeTimeout: 10s
    labels: {}

# Service account configuration
serviceAccount:
  create: true
  name: ""
  annotations:
    # For OpenShift SCC binding
    serviceaccounts.openshift.io/scc: anyuid

# Pod security context
podSecurityContext:
  runAsNonRoot: false  # Ollama containers often need root
  fsGroup: 0

# Container security context
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# Pod annotations
podAnnotations: {}

# Node selector
nodeSelector:
  nvidia.com/gpu.present: "true"

# Tolerations
tolerations: []
# - key: "nvidia.com/gpu"
#   operator: "Exists"
#   effect: "NoSchedule"

# Affinity - spread across different nodes and avoid vLLM/TGI
affinity:
  podAntiAffinity:
    # Prefer to avoid nodes with vLLM pods
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: vllm
        topologyKey: kubernetes.io/hostname
    # Prefer to avoid nodes with TGI pods
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: tgi
        topologyKey: kubernetes.io/hostname
    # Also prefer to spread Ollama instances across nodes
    - weight: 50
      podAffinityTerm:
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: ollama
        topologyKey: kubernetes.io/hostname

# Pod disruption budget
podDisruptionBudget:
  enabled: false
  # minAvailable: 1
  # maxUnavailable: 1
