{{- if .Values.storage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vllm.fullname" . }}-cache
  namespace: {{ include "vllm.namespace" . }}
  labels:
    {{- include "vllm.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  accessModes:
    {{- range .Values.storage.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.size | quote }}
  {{- if .Values.storage.storageClass }}
  {{- if (eq "-" .Values.storage.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.storage.storageClass | quote }}
  {{- end }}
  {{- end }}
  {{- with .Values.storage.selector }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
