apiVersion: v1
kind: Service
metadata:
  name: {{ include "vllm.fullname" . }}
  namespace: {{ include "vllm.namespace" . }}
  labels:
    {{- include "vllm.labels" . | nindent 4 }}
  {{- if .Values.monitoring.enabled }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.monitoring.port | default 8000 }}"
    prometheus.io/path: "{{ .Values.monitoring.path | default "/metrics" }}"
  {{- end }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 8000 }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq (.Values.service.type | default "ClusterIP") "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
    {{- if .Values.monitoring.enabled }}
    - port: {{ .Values.monitoring.port | default 8000 }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "vllm.selectorLabels" . | nindent 4 }}
  {{- if eq (.Values.service.type | default "ClusterIP") "LoadBalancer" }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
