apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tgi.fullname" . }}
  namespace: {{ include "tgi.namespace" . }}
  labels:
    {{- include "tgi.labels" . | nindent 4 }}
  annotations:
    benchmark.vllm.ai/config-name: {{ .Values.config.name | quote }}
    benchmark.vllm.ai/description: {{ .Values.config.description | quote }}
    benchmark.vllm.ai/model: {{ .Values.tgi.model | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tgi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tgi.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tgi.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: tgi
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - text-generation-launcher
          args:
            {{- range .Values.tgi.args }}
            - {{ tpl . $ | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.tgi.port }}
              protocol: TCP
          env:
            {{- if .Values.huggingface.token }}
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "tgi.fullname" . }}-hf-token
                  key: token
            {{- end }}
            {{- with .Values.tgi.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- if .Values.healthCheck.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.healthCheck.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.healthCheck.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthCheck.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.healthCheck.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.healthCheck.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.healthCheck.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.healthCheck.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthCheck.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.healthCheck.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.healthCheck.readiness.failureThreshold }}
          startupProbe:
            httpGet:
              path: {{ .Values.healthCheck.startup.path }}
              port: http
            initialDelaySeconds: {{ .Values.healthCheck.startup.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthCheck.startup.periodSeconds }}
            timeoutSeconds: {{ .Values.healthCheck.startup.timeoutSeconds }}
            failureThreshold: {{ .Values.healthCheck.startup.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data-storage
              mountPath: /data
            - name: shm
              mountPath: /dev/shm
            {{- with .Values.tgi.additionalVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        {{- if .Values.storage.enabled }}
        - name: data-storage
          persistentVolumeClaim:
            claimName: {{ include "tgi.fullname" . }}-storage
        {{- else }}
        - name: data-storage
          emptyDir: {}
        {{- end }}
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: {{ .Values.storage.shmSize }}
        {{- with .Values.tgi.additionalVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
