{{- if .Values.huggingface.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tgi.fullname" . }}-hf-token
  namespace: {{ include "tgi.namespace" . }}
  labels:
    {{- include "tgi.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if regexMatch "^[A-Za-z0-9+/]+=*$" .Values.huggingface.token }}
  # Token is already base64 encoded
  token: {{ .Values.huggingface.token }}
  {{- else }}
  # Token needs base64 encoding
  token: {{ .Values.huggingface.token | b64enc }}
  {{- end }}
{{- end }}
