apiVersion: v1
kind: Service
metadata:
  name: {{ include "tgi.fullname" . }}
  namespace: {{ include "tgi.namespace" . }}
  labels:
    {{- include "tgi.labels" . | nindent 4 }}
  annotations:
    benchmark.vllm.ai/competitor: "true"
    benchmark.vllm.ai/engine: "tgi"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "tgi.selectorLabels" . | nindent 4 }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- range .Values.service.loadBalancerSourceRanges }}
    - {{ . }}
    {{- end }}
  {{- end }}
