benchmark:
  description: Comprehensive stress testing with high load
  model: Qwen/Qwen2.5-7B
  name: vLLM vs TGI vs Ollama - Stress Test
output:
  directory: results
  generate_charts: true
  generate_report: true
  save_raw_data: true
services:
  health_check_retries: 3
  manual_urls: {}
  namespace: vllm-benchmark
  timeout_seconds: 30
test_scenarios:
  load_tests:
  - concurrent_users: 25
    duration_seconds: 120
    max_tokens: 256
    name: moderate_load
    ramp_up_seconds: 15
    target_p95_ms: 1000
    temperature: 0.7
  - concurrent_users: 50
    duration_seconds: 180
    max_tokens: 256
    name: high_load
    ramp_up_seconds: 30
    target_p95_ms: 2000
    temperature: 0.7
  - concurrent_users: 100
    duration_seconds: 300
    max_tokens: 512
    name: extreme_load
    ramp_up_seconds: 60
    target_p95_ms: 5000
    temperature: 0.7
  ttft:
    enabled: true
    iterations: 10
    max_tokens: 50
    target_ms: 100
    temperature: 0.7
    warmup_requests: 2
