{{- if .Values.huggingface.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ollama.fullname" . }}-hf-token
  namespace: {{ include "ollama.namespace" . }}
  labels:
    {{- include "ollama.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if (b64dec .Values.huggingface.token) }}
  token: {{ .Values.huggingface.token }}
  {{- else }}
  token: {{ .Values.huggingface.token | b64enc }}
  {{- end }}
{{- end }}
